### ISSUE TITLE
Schemer schemes not found.

### ISSUE THREAD

**Issue by tamton-aquib** [RRethy/nvim-base16#10]
Hey, I tried to set schemer-dark and medium colorschemes, but it says colorscheme not found.
Tried looking inside the repo folders, but no luck.
Is there any way to add it , and also I couldn't find it by googling. I dont know if I'm looking it the wrong way. Any advice?

**Comment by RRethy** [comment]
Prefix it with `base16-`, I'll make that more clear in the README.

**Comment by tamton-aquib** [comment]
Sorry, I didn't describe it clearly. (actually am new to github).
I prefixed it with base16 but couldnt get it, other colorschemes are coming allright.


![image](https://user-images.githubusercontent.com/77913442/122080090-9c7feb80-ce1b-11eb-9e5e-af74ecddc440.png)
 

And also, as i said, tried looking inside the folders, but couldn't see one for schemer.

![image](https://user-images.githubusercontent.com/77913442/122080423-e2d54a80-ce1b-11eb-86ce-388734e109e7.png)

i dont know if Im doing anything wrong.

**Comment by RRethy** [comment]
If you pull latest and try it again it should work. The builder pulls from the base16 repo but schemer-dark and schemer-medium are custom colorschemes and not in that repo, it was working for me locally because I had those files locally.
