### ISSUE TITLE
bug: attempting to index boolean value

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [RRethy/nvim-base16#14]
After the recent updates, I started getting this warning when setting any color scheme from this plugin:

`Error executing lua ...pack/packer/start/nvim-base16/lua/base16-colorscheme.lua:298: attempt to index field 'colorschemes' (a boolean value)`

**Comment by RRethy** [comment]
Can you produce a minimal config. Your PR that adds `/init` shouldn't affect behaviour since `lua/*/init.lua` files are loaded automatically when you require the directory.

**Comment by ViRu-ThE-ViRuS** [comment]
found the issue, it turns out the error was because I had another file named `colors.lua` in my config directory (rtp) which was (for some reason idk) being instead by the plugin [here](https://github.com/RRethy/nvim-base16/blob/3be30f3165278e31333b44a6dcc937653893f623/lua/base16-colorscheme.lua#L288)
