### ISSUE TITLE
Number column background color is the same as primary background, except if relativenumber

### ISSUE THREAD

**Issue by oryband** [RRethy/nvim-base16#16]
1. Should the number column be the same color as the primary background color? IIRC it should be a different one, like the background color of the lines with the relative number in the screenshot.
2. The relativenumber background is different than the other lines.

![image](https://user-images.githubusercontent.com/115387/125452531-8336525d-45e6-499f-bf41-9091fb401422.png)

**Comment by oryband** [comment]
I suspect this is a global nvim-treesitter issue, not sure. https://github.com/nvim-treesitter/nvim-treesitter/issues/1569

**Comment by RRethy** [comment]
This is intended behaviour, you can override highlights yourself with normal Vim mechanisms if there is something you would like to change.

**Comment by RRethy** [comment]
Worth mentioning this is not a shot-for-shot remake of base16-vim, there are a few highlight groups which differ.

**Comment by oryband** [comment]
Thanks.
