### ISSUE TITLE
How to use terminal colors

### ISSUE THREAD

**Issue by AntoinePrv** [RRethy/nvim-base16#17]
Hi and thank you for providing this plugin!

I'm using [chriskempson/base16-shell](https://github.com/chriskempson/base16-shell) to set colors in the shell and then have other tools automatically pick them up.
Before switching to tree-sitter highlighting and this plugin, I was using [chriskempson/base16-vim](https://github.com/chriskempson/base16-vim), which [seems](https://github.com/chriskempson/base16-vim/blob/6191622d5806d4448fa2285047936bdcee57a098/colors/base16-3024.vim#L52) (or so I understand) to pick colors from the terminal using `let s:cterm03 = "08"`...

I tried setting such colors using `require('base16-colorscheme').setup` as documented but all colors turn gray. I tried setting 
`base03 = 08`, `base03 = '08'`... but none work. RGB color codes such as `base03='#a06949'` work as intended.

**Comment by AntoinePrv** [comment]
Looks like we need to set `ctermfg` and `ctermbg`. In [chriskempson/base16-vim](https://github.com/chriskempson/base16-vim), they are set with a number in [0, 21] unconditionally of the theme.
Is this an addition you'd be willing to add?

**Comment by jdsutherland** [comment]
It sounds like there's some confusion here. Once you install this plugin, you need to set the specific theme you want to use: e.g., `colorscheme base16-tomorrow-night`. You shouldn't have to make any edits to the plugin itself.

In the plugin, the colors are set here: https://github.com/RRethy/nvim-base16/blob/f9b28409a6b6b6a4e6722fb3b7c866ae3e3b2866/lua/base16-colorscheme.lua#L58-L281. If you want to tweak any of these, you can override them in `require('base16-colorscheme').setup`.

**Comment by AntoinePrv** [comment]
Found out [fnune/base16-vim](https://github.com/fnune/base16-vim) fork of [chriskempson/base16-vim](https://github.com/chriskempson/base16-vim) is kept up to date with new neovim features (tree-sitter, LSP...) so that works for me.
