### ISSUE TITLE
Use cterm colors instead of gui colors

### ISSUE THREAD

**Issue by akorchemniy** [RRethy/nvim-base16#18]
One advantage of of the original base16 is that it's possible to use with terminals that don't support true color (for example mosh). This implementation enables termguicolors, which breaks mosh. Is there a hard dependency on termgui or can the theme use ctermfg/bg instead?

**Comment by RRethy** [comment]
`cterm` is not implemented and I don't have plans on implementing. I'm open to PRs which add it and I'll review.

**Comment by mdkcore0** [comment]
Hey, this breaks colors if using [base16-shell from tinted-theming](https://github.com/tinted-theming/base16-shell)
with this commit:
![image](https://github.com/RRethy/nvim-base16/assets/1218078/66142d02-5ef3-4d5e-9d2c-f7bd6a8bc0e5)

the commit before this one (3c6a56016cea7b892f1d5b9b5b4388c0f71985be):
![image](https://github.com/RRethy/nvim-base16/assets/1218078/1e786207-a0c8-43ad-b3e4-3a57ee2a1f1e)

or am I missing something here?

**Comment by RRethy** [comment]
Try adding `set termguicolors` in your init file.

**Comment by mdkcore0** [comment]
oh, thanks @RRethy, that fixed it for me! (used `vim.o.termguicolors=true` on lua for anyone wondering about that)

**Comment by RRethy** [comment]
For lua, you should use `vim.opt.termguicolors=true`. As a general rule of thumb, `vim.opt` is preferred in init files.
