### ISSUE TITLE
nvim-base16, treesitter and yaml: odd highlighting

### ISSUE THREAD

**Issue by kadrach** [RRethy/nvim-base16#19]
The commit db39dbb0a647bd3a05778e81dd9381193013476f overhauls a number of highlight groups, and to me changes the expected behavior of YAML highlighting (but perhaps the treesitter grammar is incorrect here!).

Before:
![Screen Shot 2021-09-11 at 11 05 42 am](https://user-images.githubusercontent.com/206176/132931375-7926e796-d2c2-4f93-84ad-b44afcba4ae6.png)

After:
![Screen Shot 2021-09-11 at 11 09 26 am](https://user-images.githubusercontent.com/206176/132931378-be19b656-e6cf-40cf-812e-8dc1f177a6b3.png)

**Comment by kadrach** [comment]
Probably related to https://github.com/ikatyang/tree-sitter-yaml/issues/28.

**Comment by RRethy** [comment]
Needs more details, I don't know what you mean.
