### ISSUE TITLE
Inconsistent python docstring coloring

### ISSUE THREAD

**Issue by loiccoyle** [RRethy/nvim-base16#20]
Hi,
I'm getting some weird behaviour whith python docstrings, depending on the indentation level and the white space within the docstring I get different coloring. See screenshots bellow.

Note: I'm using the base16-gruvbox-dark-hard colorscheme.

![image](https://user-images.githubusercontent.com/33181239/133096125-dc21d93e-ccd2-47c6-9e48-fa5165b66501.png)

![image](https://user-images.githubusercontent.com/33181239/133096193-54dab473-1b25-47b9-9fa6-8f2b06c99d0d.png)

![image](https://user-images.githubusercontent.com/33181239/133096283-1646d31e-8bf8-4a1b-9944-0e628f32833e.png)

I expect the docstring to be all green regardless of the whitespace and indentation within.

**Comment by RRethy** [comment]
This would be handled by nvim-treesitter (assuming you are using treesitter). nvim-base16 only defines the highlight groups not where they are placed. https://github.com/nvim-treesitter/nvim-treesitter or even in the parser's repo would be the best bet.
