### ISSUE TITLE
Return syntactic sugar for setting highlight groups

### ISSUE THREAD

**Issue by mnarrell** [RRethy/nvim-base16#25]
Is it possible to re-export the syntactic sugar for setting highlight groups in `base16-colorscheme.lua`?  This was a nice ability I was using to set additional highlight groups.

```
-- local colorscheme = require('colorscheme')
-- local hi = colorscheme.highlight
-- hi.Comment = { guifg='#ffffff', guibg='#000000', gui='italic', guisp=nil }
-- hi.LspDiagnosticsDefaultError = 'DiagnosticError' -- Link to another group
```
vs
```
local hi = setmetatable({}, { ...
```

**Comment by mnarrell** [comment]
Hey @RRethy, thanks for this!  I realize there’s no obligation to support undocumented functions, but I appreciate your consideration here.

**Comment by RRethy** [comment]
Nw, I had thought about adding better functionality to override highlights but had not gotten around to it, maybe I'll expand on it since it seems there's a few people using it.
