### ISSUE TITLE
Diagnostic signs override locally set values

### ISSUE THREAD

**Issue by nicknisi** [RRethy/nvim-base16#33]
It looks like this was introduced in 841a5e1d8f1c95fff7597ab5b96c35cfd3818d1e. With this set, it's overriding the custom icons I have set for Error, Warning, etc. Is there a way to override these? Thanks!

**Comment by RRethy** [comment]
Where do you define the icons? If you put it after any call to `:colorscheme ...` then it should override `nvim-base16`. That being said, I'm going to revert that commit, thinking about it a bit more and it's a bit of an overreach for this plugin.
