### ISSUE TITLE
[Plugin Request] Can you add https://github.com/p00f/nvim-ts-rainbow support?

### ISSUE THREAD

**Issue by shaunsingh** [RRethy/nvim-base16#36]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/152615615-8ba285bf-6758-48ae-8ddf-5384bb154b8d.png">

Thanks for the plugin! One small issue, the colors for ts-rainbow don't fit with the theme, is it possible to add support for it?

**Comment by RRethy** [comment]
I don't use that plugin so I won't add support for it, but I'm open to people opening a PR to add support which I can review and merge.

**Comment by EtiamNullam** [comment]
@RRethy I believe this can be closed.
