### ISSUE TITLE
Non-hex colors no longer work

### ISSUE THREAD

**Issue by arguablykomodo** [RRethy/nvim-base16#38]
I have a custom colorscheme that uses `transparent` as its `base00` color, but after ca3ee8343118c53b8bad02d96466be2417f1f855 this no longer works since it now requires the color to be in hexadecimal. Are non-hexadecimal colors no longer supported or is this considered a bug?

**Comment by RRethy** [comment]
I put in a guard for this use case, but tbh it's kind of defeating the purpose of using base16 colorscheme when you have 15 colours.
