### ISSUE TITLE
Invert selection

### ISSUE THREAD

**Issue by EtiamNullam** [RRethy/nvim-base16#44]
Is there any chance to have an option for inverted selection - switch foreground with background for highlighted text - similar to how gruvbox community does it?

![image](https://user-images.githubusercontent.com/10875340/164869482-26260566-fb99-4fd7-9ad6-f1c562512abe.png)

**Comment by RRethy** [comment]
You can override the colorscheme with normal Neovim mechanisms, `:hi Visual gui=reverse` will do the trick.
