### ISSUE TITLE
Change the colorscheme mode to make it compatible with other base16 colorsheme

### ISSUE THREAD

**Issue by mayanksuman** [RRethy/nvim-base16#5]
Almost all base16 plugin have name prefixed by `base16-` (refer to [this repo](https://github.com/chriskempson/base16)). However the colorscheme name provided by this plugin do follow the norm leading to issue regarding interfacing with other software. 

For instance, I use [base16-shell](https://github.com/chriskempson/base16-shell) which produces a file `~/.vimrc_background`. The file can be sourced directly in nvim to get a same colorsheme in nvim. However, as the colorscheme name in this plugin differ, so this lead to error.

**Comment by RRethy** [comment]
There is no issue interfacing with [base16-shell](https://github.com/chriskempson/base16-shell). Look at [this line of code](https://github.com/chriskempson/base16-shell/blob/ce8e1e540367ea83cc3e01eec7b2a11783b3f9e1/profile_helper.sh#L24), the produced `~/.vimrc_background` contains code to set Vim colours via the `:h :colorscheme` mechanism. However, [nvim-base16](https://github.com/RRethy/nvim-base16) does not use the `:h :colorscheme` mechanism at all (notice the lack of a `colors/` directory). If you want to utilize the `:h :colorscheme` mechanism you can create a colorscheme file (e.g. `colors/nord.vim` with the lines `lua require('colorscheme').setup('nord')` and `let g:colors_name='nord'` (something along those lines).

If you have a valid example where naming actually breaks things I will consider it.
