### ISSUE TITLE
Colorscheme not updating for `bufferline.nvim`

### ISSUE THREAD

**Issue by 4e554c4c** [RRethy/nvim-base16#55]
I'm an avid user of nvim-base16 and I recently started to use [bufferline.nvim](https://github.com/akinsho/bufferline.nvim). I also automatically change the colorscheme of my desktop (incl. neovim) on sunrise and sunset. This amounts to reloading a lua file that looks like
```lua
vim.opt.background = light
vim.cmd([[colorscheme base16-atelier-forest-light]])
```

This works great for everything except the bufferline, which does not change _to_ a base16 theme and instead stays the previous theme. I have tested with different themes, and only nvim-base16 exhibits this behaviour (i.e. gruvbox -> base16 fails to work, but base16 -> gruvbox works fine).

See akinsho/bufferline.nvim#490, which this issue supersedes.

**Comment by RRethy** [comment]
I'm not sure I see how this is an issue with nvim-base16, this plugin is just a glorified runner for `:highlight ...` commands. You should reopen the issue in bufferline, if you can figure out the reload mechanism for colors (instead of just using highlight group) it's using then maybe something can be done.

**Comment by 4e554c4c** [comment]
Hi, I've finally traced this to other colorschemes calling `highlight clear`, right before setting `g:colors_name`.
For example, rose-pine does this here: https://github.com/rose-pine/neovim/blob/main/lua/rose-pine.lua#L69

For example, adding the line `hi clear` to the beginning of `colors/colorscheme base16-atelier-forest-light.vim` fixes this issue.

Can we re-open?

**Comment by RRethy** [comment]
I'm not entirely clear why I removed that in the first place 🤔 I see it removed last year in my git log but without a clear commit message.
