### ISSUE TITLE
feature request: doautocmd ColorScheme when specifying colors to the setup function

### ISSUE THREAD

**Issue by goolord** [RRethy/nvim-base16#61]
motivation: i have some personal configuration that changes the colors of highlight groups based on `g:terminal_color_*` which is setup to be called every time the `ColorScheme` event is fired. calling `setup` with colors is morally changing the colorscheme, but does not fire the `ColorScheme` event, so if the colors change in that way (via `PackerCompile` or loading a different colorscheme) the my code isn't executed. 

there might be other users / plugins that rely on this behavior ¯\\\_(ツ)\_/¯

**Comment by RRethy** [comment]
You should either be calling `:colorscheme <colorscheme_name>` from your init file (for builtin schemes) or putting your `.setup` call in a `colors/<colorscheme_name>.lua` file and calling `:colorscheme <colorscheme_name>` (for custom schemes). Calling `.setup` from `init.lua` is circumventing the `:colorscheme` command and the reason why the autocmd isn't fired.
