### ISSUE TITLE
Add support for new Treesitter highlight groups

### ISSUE THREAD

**Issue by lpraneis** [RRethy/nvim-base16#62]
Treesitter commit https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f removed support for legacy hightlight groups TS*. and so highlighting via this colorscheme is currently broken for treesitter groups.

**Comment by RRethy** [comment]
Yea I saw that update last night, haven't had a chance to update things yet. Sometime this week I will.

**Comment by RRethy** [comment]
I anyone see highlights go out of wack, comment here and we can get them fixed. I mostly automated this with substitution commands and macros.
