### ISSUE TITLE
Neovim error on startup from latest commit

### ISSUE THREAD

**Issue by viktorholk** [RRethy/nvim-base16#64]
I am using Packer.
I get this error on startup on the latest nvim-base16
<img width="845" alt="image" src="https://user-images.githubusercontent.com/45604642/199001237-7f6a952d-1b62-4036-a679-ae7b244a3810.png">

I get no error on commit `d2a56671ed19fb471acf0c39af261568ea47ee26 `
<img width="587" alt="image" src="https://user-images.githubusercontent.com/45604642/199000908-51c5656b-c20b-4067-a0f9-605700e9dc2b.png">

**Comment by RRethy** [comment]
What's your version of Neovim? The most recent commit was fixing a breaking change to nvim-treesitter but you might be using a version of Neovim that doesn't support the new nvim-treesitter highlight groups.

**Comment by viktorholk** [comment]
Yes updating it fixed it for me
I updated from v0.7.2 to v0.8.0
Thanks
