### ISSUE TITLE
How to set a dark / light theme?

### ISSUE THREAD

**Issue by louwers** [RRethy/nvim-base16#66]
Is it possible to set both a dark and a light theme with this? I.e. `set bg=dark` and `set bg=light`.

**Comment by RRethy** [comment]
It's not possible and I probably wouldn't be open to PRs which add this functionality since the `'bg'` mechanism is poorly designed IMO and doesn't fit with base16 anyways. Since these are base16 colorschemes though there are many light colorschemes for each dark colorscheme.
