### ISSUE TITLE
Install using Packer

### ISSUE THREAD

**Issue by pguerin3** [RRethy/nvim-base16#67]
For the newbies to Packer, do the following to install and use this repo:

1) Add this to your settings.lua file. eg the everforest color scheme.
```
vim.cmd('colorscheme base16-everforest')
```

2) Add this to your init.lua file:
```
require('settings')
require('base16-colorscheme')
```

3) Add this to your plugins.lua file (for Packer):
```
  use {'RRethy/nvim-base16'}
```

4) Go through the motions inside NeoVim to install the repo:
```
:PackerCompile
:PackerClean
:PackerInstall
:PackerSync
```

**Comment by RRethy** [comment]
These are instructions related to your specific config.
