### ISSUE TITLE
Wrong color on popup windows

### ISSUE THREAD

**Issue by pronvis** [RRethy/nvim-base16#85]
I am moving from my old config to new one on Neovim wich support Lua, so I rewriting it enterily from scratch.
For some reason base16 theme looks bad, here is the video: 

https://github.com/RRethy/nvim-base16/assets/228536/c1bd3c30-780d-429b-85ea-d170eb7f53cb

No idea how to fix it myself :(
Here is the config: https://github.com/pronvis/configs/tree/nvim_to_lua_cfg/nvim

**Comment by pronvis** [comment]
Looks like it is telescope related issue (cause popup is from telescope). 
Popup windows from https://github.com/ThePrimeagen/harpoon looks fine

**Comment by pronvis** [comment]
I found fix, but have no idea why it works:
```lua
require('base16-colorscheme').with_config({
    telescope = false,
})
require('base16-colorscheme').setup({
    base00 = '#2d2d2d',
    base01 = '#393939',
    base02 = '#515151',
    base03 = '#999999',
    base04 = '#b4b7b4',
    base05 = '#cccccc',
    base06 = '#e0e0e0',
    base07 = '#ffffff',
    base08 = '#f2777a',
    base09 = '#f99157',
    base0A = '#ffcc66',
    base0B = '#99cc99',
    base0C = '#66cccc',
    base0D = '#6699cc',
    base0E = '#cc99cc',
    base0F = '#a3685a'
})
```
Colors is default ones, so there is no reason to setup them, but if you remove it, then Telescope popup window will be not fixed. 
So
```lua
require('base16-colorscheme').with_config({
    telescope = false,
})
``` alone does not do the job - have no idea why.

**Comment by RRethy** [comment]
Probably:

```lua
require('base16-colorscheme').with_config({
    telescope = false,
    telescope_borders = true,
})
```

**Comment by pronvis** [comment]
@RRethy thanks, but for some reason now it works even without colors rewrites. Dont know why. 
I moved to lazy_vim instead of packer & use this to set theme in nvim:
```lua
local fn = vim.fn
local cmd = vim.cmd
local set_theme_path = "$HOME/.config/tinted-theming/set_theme.lua"
local is_set_theme_file_readable = fn.filereadable(fn.expand(set_theme_path)) == 1 and true or false

if is_set_theme_file_readable then
    cmd("let base16colorspace=256")
    cmd("source " .. set_theme_path)
end
```
