### ISSUE TITLE
Support new capture names

### ISSUE THREAD

**Issue by MaienM** [RRethy/nvim-base16#88]
nvim-treesitter introduced a [breaking change](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583) affecting colorschemes. The [commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0) for this change includes a good overview of what token changed to what.

**Comment by RRethy** [comment]
Oh good, I was worried nvim-treesitter wouldn't ship breaking changes in 2024. I'll try to fix it later today.
